{{- if .Values.ebpf.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudcondom-ebpf
  namespace: {{ include "cloudcondom.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudcondom-ebpf
    {{- include "cloudcondom.labels" . | nindent 4 }}
{{- end }}
