{{- if .Values.ebpf.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudtaser-ebpf
  namespace: {{ include "cloudtaser.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudtaser-ebpf
    {{- include "cloudtaser.labels" . | nindent 4 }}
{{- end }}
