apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudcondom-operator
  namespace: {{ include "cloudcondom.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudcondom-operator
    {{- include "cloudcondom.labels" . | nindent 4 }}
