apiVersion: v1
kind: Service
metadata:
  name: cloudtaser-operator-webhook
  namespace: {{ include "cloudtaser.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudtaser-operator
    {{- include "cloudtaser.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
  selector:
    control-plane: controller-manager
