apiVersion: v1
kind: Service
metadata:
  name: cloudcondom-operator-webhook
  namespace: {{ include "cloudcondom.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudcondom-operator
    {{- include "cloudcondom.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
  selector:
    control-plane: controller-manager
