apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcondom-operator
  namespace: {{ include "cloudcondom.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudcondom-operator
    {{- include "cloudcondom.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: cloudcondom-operator
        {{- include "cloudcondom.labels" . | nindent 8 }}
    spec:
      serviceAccountName: cloudcondom-operator
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ include "cloudcondom.operator.image" . }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
            - --webhook-port={{ .Values.operator.webhook.port }}
          env:
            - name: CLOUDCONDOM_INIT_IMAGE
              value: {{ include "cloudcondom.wrapper.image" . }}
          ports:
            - containerPort: {{ .Values.operator.webhook.port }}
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: cert
          emptyDir: {}
