apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudtaser-operator
  labels:
    app.kubernetes.io/name: cloudtaser-operator
    {{- include "cloudtaser.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudtaser-operator
subjects:
  - kind: ServiceAccount
    name: cloudtaser-operator
    namespace: {{ include "cloudtaser.namespace" . }}
