apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudtaser-operator
  namespace: {{ include "cloudtaser.namespace" . }}
  labels:
    app.kubernetes.io/name: cloudtaser-operator
    {{- include "cloudtaser.labels" . | nindent 4 }}
