namespace: cloudtaser-system

imagePullSecrets: []

operator:
  replicaCount: 1
  image:
    repository: ghcr.io/skipopsltd/cloudtaser-operator
    tag: "v0.4.8-amd64"
    pullPolicy: Always
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  webhook:
    port: 9443
    failurePolicy: Fail
    timeoutSeconds: 10

wrapper:
  image:
    repository: ghcr.io/skipopsltd/cloudtaser-wrapper
    tag: "v0.0.9-amd64"

s3proxy:
  image:
    repository: ghcr.io/skipopsltd/cloudtaser-s3-proxy
    tag: "v0.2.2-amd64"

ebpf:
  enabled: true
  image:
    repository: ghcr.io/skipopsltd/cloudtaser-ebpf
    tag: "v0.1.4-amd64"
    pullPolicy: Always
  enforceMode: true
  logAll: false
  reactiveKill: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
